;aperture wheel file generated by EAGLE
;remove the above line to prevent this file from being overwritten!

D10      round     0.1340inch
D11      draw      0.0680inch
D12      octagon   0.0600inch
D13      round     0.0740inch
D14      draw      0.0600inch
D15      round     0.0520inch
